# Julia- Linear Algebra 
---

In this more math-centric notebook, we will understand how you can leverage Julia to perform all sorts of algrbraic operations, that are a key to a bunch of operations involved in Data Science.

## Importing Dependencies
---

Here are some of the important modules in Julia:

* __LinearAlgebra__: As the name suggests, it provides a set of very powerful linear algrebra functions.
* __SparseArrays__: Another popular linear algrbra module in Julia
* __Images__: Used for handling image data

In [1]:
using LinearAlgebra
using SparseArrays
using Images
using MAT

For checking the documentation associated with any module or any methods associated with the module, use the '?' help operator.

In [2]:
?LinearAlgebra

search: LinearAlgebra



Linear algebra module. Provides array arithmetic, matrix factorizations and other linear algebra related functionality.


Now let us see how we can create some arrays using the `LinearAlgebra` module.

In [3]:
# creating a matrix of random numbers
arr1 = rand(3,5)

3×5 Array{Float64,2}:
 0.631873  0.27411   0.0178048  0.776951  0.945021
 0.786527  0.593411  0.258996   0.644373  0.773138
 0.085794  0.781808  0.966103   0.935955  0.449427

In [4]:
# creating a matrix of random numbers from standard normal dist
arr2 = randn(5,5)

5×5 Array{Float64,2}:
  0.255533   0.392046   0.0185083   0.744757  -1.79027
 -0.886307  -1.86309    0.762894    1.31321    1.25415
 -0.328278   0.242044  -0.74273     0.230575  -0.716223
  1.62397    0.636272  -1.46299    -0.557447   0.38613
 -0.796368   0.589645   0.0677677   0.552996   0.367853

Now let us have a look at some of the basic matrix operations that you can perform on matrices/vectors using `LinearAlgebra`.

In [5]:
# transpose of a matrix
arr1_T = arr1'

5×3 Adjoint{Float64,Array{Float64,2}}:
 0.631873   0.786527  0.085794
 0.27411    0.593411  0.781808
 0.0178048  0.258996  0.966103
 0.776951   0.644373  0.935955
 0.945021   0.773138  0.449427

In [6]:
# transpose of a vector
vec1 = randn(10)
vec1_T = vec1'

1×10 Adjoint{Float64,Array{Float64,1}}:
 -2.38514  -0.681694  0.914683  -0.237827  …  -0.829157  0.82008  0.318454

In [7]:
# inverse of a matrix
arr2_inv = inv(arr2)

# checking if it's an inverse
norm(arr2_inv * arr2 - I(5))

5.260814360540369e-16

As we can see, the norm of the matrx __A<sup>-</sup> * A__ and __I__ (identity matrix) is a negligible number.

In [8]:
# for a real valued matrix, adjoint == transpose
adjoint(arr1) == transpose(arr1)

true

Now let us have a look at some of the matrix multiplication operations.

In [9]:
A = rand(5,5)
x = rand(5,4);

In [10]:
B = A * x

5×4 Array{Float64,2}:
 0.75579   0.556175  0.589132  0.850134
 1.46806   1.5222    1.37189   1.7645
 0.928255  1.02621   0.67609   0.935736
 1.30513   1.43543   1.0254    1.57297
 1.02376   1.12445   0.630382  1.14419

In [11]:
# will result in error 
# if n_columns of first matrix != n_rows of second matrix
y = rand(6,4)
C = A * y

LoadError: DimensionMismatch("A has dimensions (5,5) but B has dimensions (6,4)")

Now let us see a very powerful operator in Julia— The backslash or inversed division operator (\).

In [12]:
X = A \ B  # inv(A) * A * x = inv(A) * B => x = inv(A) * B

5×4 Array{Float64,2}:
 0.40667   0.86808    0.180387   0.365725
 0.495175  0.689242   0.892334   0.873119
 0.803149  0.579325   0.500757   0.705469
 0.201754  0.0701747  0.267047   0.29294
 0.163542  0.196368   0.0283078  0.31822

In [13]:
# norm of the matrices tends to 0
norm(X - x)

4.1890824311343064e-15

The inverse division operator can be used to solve matrices quickly. In case the matrix A is not invertible, the solution obtained by the inverse division will be such that the norm of x - x_calc will be minimum.

Now let us have a look at the different kinds of factorizations using the `LinearAlgebra` module.

#### 1. LU Decomposition
---

Note- True LU (or LDU) decomposition is only possible for square matrices that are invertible, and have all the leading minors as 0. On the other hand, all the square matrices can be factorized into the PLU form.  

Therefore, LU factorization can be expressed in the form of a linear equation as:
`A = P.L.U`

Now let us see how you can perform LU factorization using Julia.

In [14]:
A = rand(4, 4)

4×4 Array{Float64,2}:
 0.89313   0.0989117  0.0323763  0.341025
 0.28557   0.306644   0.977148   0.0360708
 0.105629  0.256303   0.391752   0.395309
 0.459913  0.998694   0.192612   0.829403

In [15]:
# performing LU factorization on A
LuA = lu(A)

LU{Float64,Array{Float64,2}}
L factor:
4×4 Array{Float64,2}:
 1.0       0.0       0.0      0.0
 0.514945  1.0       0.0      0.0
 0.319741  0.290177  1.0      0.0
 0.118269  0.258087  0.37403  1.0
U factor:
4×4 Array{Float64,2}:
 0.89313  0.0989117  0.0323763   0.341025
 0.0      0.94776    0.17594     0.653794
 0.0      0.0        0.915742   -0.262685
 0.0      0.0        0.0         0.284492

In [16]:
# verifying if the factorization was successful by checking the norn
norm(LuA.P*A - LuA.L*LuA.U)

0.0

As you can see, the norm tends to approach 0 (Not Exactly 0 due to machine precision).

#### 2. QR Factorization
---

QR factorization can be used to factorize a rectangular matrix. 
Here A is the matrix of size m x n that we wish to decompose, Q a matrix with the size m x m, and R is an upper triangle matrix with the size m x n.

The QR factorization can be expressed in terms of an algebraic equation as follows:
`A = QR`
This is how you can perform the factorization using Julia:

In [17]:
# creating a rectangular 4x5 array 
B = rand(4, 5)

4×5 Array{Float64,2}:
 0.615109  0.176513  0.506827   0.188952  0.379396
 0.776045  0.063903  0.214639   0.014946  0.384126
 0.821165  0.216574  0.0889405  0.499886  0.660166
 0.978466  0.795466  0.382417   0.258609  0.926754

In [18]:
# performing QR decomposition
qrB = qr(B)

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
4×4 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.380574  -0.175457   0.849558   -0.320357
 -0.480147  -0.545794  -0.0702203   0.683108
 -0.508063  -0.273193  -0.521192   -0.628964
 -0.605387   0.772457  -0.0409746   0.187452
R factor:
4×5 Array{Float64,2}:
 -1.61627  -0.689457  -0.572641   -0.489619   -1.22528
  0.0       0.489448   0.0650278   0.0218886   0.259303
  0.0       0.0        0.353483   -0.111657   -0.0867005
  0.0       0.0        0.0        -0.316256   -0.100641

In [19]:
# checking if the factorization was successfully performed
norm(qrB.Q*qrB.R - B)

3.825842074281555e-16

Once again, as we can see, the norm came out to be almost zero, due to the machine precision. Hence, this confirms that the factorization was a valid one.

#### 3. Cholesky Factorization
---

One this to note is that for a matrix to be Cholesky-factorizable, it needs to be a positive definite matrix. 

```
Cholesky factorization decomposses a matrix A into two parts:
  1. A lower triangular matrix L
  2. A conjugate transpose of matrix L, L* 

This can be expressed algebraicly as:
  A = LL*
```

Let us see how we can perform Cholesky factorization using Julia.

In [27]:
# defining a matrix C
C = rand(5, 5)
C = C*C'

5×5 Array{Float64,2}:
 0.781327  0.794665  0.894946  0.686603  0.931412
 0.794665  1.50148   1.29782   0.900533  1.2269
 0.894946  1.29782   1.82571   1.24699   1.78543
 0.686603  0.900533  1.24699   1.43983   1.27417
 0.931412  1.2269    1.78543   1.27417   2.0282

In [28]:
# checking if the defined matrix is a positive definite matrix
isposdef(C)

true

In [31]:
# performing cholesky factorization
cholC = cholesky(C)

Cholesky{Float64,Array{Float64,2}}
U factor:
5×5 UpperTriangular{Float64,Array{Float64,2}}:
 0.883927  0.899016  1.01247   0.776765  1.05372
  ⋅        0.832619  0.465519  0.24286   0.335798
  ⋅         ⋅        0.764145  0.454738  0.735794
  ⋅         ⋅         ⋅        0.755447  0.0523278
  ⋅         ⋅         ⋅         ⋅        0.510859

In [32]:
# checking if the factorization was successful
norm(cholC.L * cholC.U - C)

2.482534153247273e-16

As we can see, the factorization was successful. The reason is because the norm almost tends to 0 (not exactly 0 due to computer precision).

Now we are going to have a look at one-method-do-all factorization function in Julia that automatically detects the kind of matrix that you are using, then performs the best suitable factorization for that given matrix. 

> One quirk here is that since the matrix will be evaluated on various parameters for deciding the most suitable factorization, this method tends to be generally slower than when you manually define the kind of factorization that you want. So, it's faster to know what is the best suitable factorization for a given matrix than letting Julia decide on its own. 

#### 4. Factorize Method
---

Let's just simply take a look at the `factorize()` method's documentation to see how it works. 

In [33]:
?factorize

search: factorize Factorization factorial



```
factorize(A)
```

Compute a convenient factorization of `A`, based upon the type of the input matrix. `factorize` checks `A` to see if it is symmetric/triangular/etc. if `A` is passed as a generic matrix. `factorize` checks every element of `A` to verify/rule out each property. It will short-circuit as soon as it can rule out symmetry/triangular structure. The return value can be reused for efficient solving of multiple systems. For example: `A=factorize(A); x=A\b; y=A\C`.

| Properties of `A`          | type of factorization                      |
|:-------------------------- |:------------------------------------------ |
| Positive-definite          | Cholesky (see [`cholesky`](@ref))          |
| Dense Symmetric/Hermitian  | Bunch-Kaufman (see [`bunchkaufman`](@ref)) |
| Sparse Symmetric/Hermitian | LDLt (see [`ldlt`](@ref))                  |
| Triangular                 | Triangular                                 |
| Diagonal                   | Diagonal                                   |
| Bidiagonal                 | Bidiagonal                                 |
| Tridiagonal                | LU (see [`lu`](@ref))                      |
| Symmetric real tridiagonal | LDLt (see [`ldlt`](@ref))                  |
| General square             | LU (see [`lu`](@ref))                      |
| General non-square         | QR (see [`qr`](@ref))                      |

If `factorize` is called on a Hermitian positive-definite matrix, for instance, then `factorize` will return a Cholesky factorization.

# Examples

```jldoctest
julia> A = Array(Bidiagonal(fill(1.0, (5, 5)), :U))
5×5 Array{Float64,2}:
 1.0  1.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  0.0
 0.0  0.0  1.0  1.0  0.0
 0.0  0.0  0.0  1.0  1.0
 0.0  0.0  0.0  0.0  1.0

julia> factorize(A) # factorize will check to see that A is already factorized
5×5 Bidiagonal{Float64,Array{Float64,1}}:
 1.0  1.0   ⋅    ⋅    ⋅
  ⋅   1.0  1.0   ⋅    ⋅
  ⋅    ⋅   1.0  1.0   ⋅
  ⋅    ⋅    ⋅   1.0  1.0
  ⋅    ⋅    ⋅    ⋅   1.0
```

This returns a `5×5 Bidiagonal{Float64}`, which can now be passed to other linear algebra functions (e.g. eigensolvers) which will use specialized methods for `Bidiagonal` types.
